services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - 8000:80
    volumes:
      - ./_docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html
    depends_on:
      - app
    container_name: laravel_nginx

  app:  
    build:
      context: _docker/app
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    container_name: laravel

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3316:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: lardocker
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: laravel_mysql

  composer:
    build:
      context: _docker/app
      dockerfile: composer.Dockerfile
    volumes:
      - ./:/var/www/html

  artisan:
    build:
      context: _docker/app
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
